name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Why is this useful?
    validations:
      required: true
